/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projjavaPOO;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      Classe Vertebrado = new Classe();
      Classe Vertebrado2 = new Classe();
      Classe Vertebrado3 = new Classe();
      Classe Vertebrado4 = new Classe();
      /* Animal f(x): Necessita de classe existente*/
      /* Filo f(x): Necessita de nome*/
      /*Especie e(x): Necessita de nome, idade int, sexo, altura double e peso int */
      Vertebrado.a1 = new Animal (new Mamifero());
      Vertebrado.f1 = new Filo("Chordata");
      Vertebrado.e1 = new Especie("Baleia", 50, "Masculino", 3.52, 2000);
      Vertebrado.a2 = new Animal (new Peixes());
      Vertebrado.f2 = new Filo("Cordados");
      Vertebrado.e2 = new Especie("Tubarao Martelo", 25, "Feminino", 2.23, 400);
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      
      Vertebrado2.a1 = new Animal (new Aves());
      Vertebrado2.f1 = new Filo("Cordados");
      Vertebrado2.e1 = new Especie("Falcao-Americano", 15, "Feminino", 0.74, 10);
      Vertebrado2.a2 = new Animal (new Peixes());
      Vertebrado2.f2 = new Filo("Cordados");
      Vertebrado2.e2 = new Especie("Peixe-Leao", 9, "Masculino", 0.85, 11);
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      
      
      
      Vertebrado3.a1 = new Animal (new Anfibio());
      Vertebrado3.f1 = new Filo("Cordados");
      Vertebrado3.e1 = new Especie("Sapo-Flecha", 3, "Feminino", 0.22, 3);
      Vertebrado3.a2 = new Animal (new Mamifero());
      Vertebrado3.f2 = new Filo("Chordata");
      Vertebrado3.e2 = new Especie("Humano", 18, "Masculino", 1.75, 90);
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      
      Vertebrado4.a1 = new Animal (new Reptel());
      Vertebrado4.f1 = new Filo("Cordados");
      Vertebrado4.e1 = new Especie("Crocodilo", 23, "Feminino", 1.01, 160);
      Vertebrado4.a2 = new Animal (new Peixes());
      Vertebrado4.f2 = new Filo("Cordados");
      Vertebrado4.e2 = new Especie("Cavalo-Marinho", 10, "Masculino", 1.23, 10);
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      Vertebrado.celulas.add(new celula());
      
      System.out.println(Vertebrado.a1.Grito(500));
      System.out.println(Vertebrado.a2.Grito(200));
      System.out.println(Vertebrado2.a1.Grito(100));
      System.out.println(Vertebrado2.a2.Grito(5));
      System.out.println(Vertebrado3.a1.Grito(30));
      System.out.println(Vertebrado3.a2.Grito(80));
      System.out.println(Vertebrado4.a1.Grito(31));
      System.out.println(Vertebrado4.a2.Grito(3));
     
      
      
    }
}
